### ISSUE TITLE
what is context?

### ISSUE THREAD

**Issue by jw9603** [raruidol/ArgumentMining23-Fallacy#1]
Hello. 

I found your paper quite interesting. 

Could you clarify what adding context to existing data means in the experiments?(4.2 (ii) and fallacy_corpus.json)

Thank you!

**Comment by raruidol** [comment]
Hi Jiwon,

Thanks for the interest. The context, as described in the paper (https://aclanthology.org/2023.argmining-1.1/) is defined as follows:

> _A sample in our fallacy detection corpus consists of a short snippet of text where the fallacious (or not) reasoning has been identified, a natural language context in which the fallacy has been detected (a paragraph in the case of the debates, and the previous comment of the text snippet in the case of the social media discussions), and the annotated label. In order to homogenise the natural language context in data belonging to both corpora, for the samples extracted from the debate corpus we con- sidered as the context only the sentences before and after the text snippet._

The dataset used to evaluate the models in the section 5 when including the context to the input is the one called "fallacy_corpus_context.json" which contains the snippet + context sentence(s) before/after the snippet.

I hope that this informations helps :)

Ramon
